module.exports = [
    "If Alan Wake failed a test, he'd be Alan Re-Take.",
    "If Alan Wake was a part human, part lizard (or you know, a screaming plant), he would be Alan Mandrake.",
    "If Alan Wake was sealing a deal, he would be Alan Handshake.",
    "When Alan Wake fell in that body of water, he became Alan Lake.",
    "If Alan Wake was a thief, he'd be Alan Take.",
    "If Alan Wake gathered leaves, he'd be Alan Rake.",
    "If Alan Wake made bread for a living, he'd be Alan Bake.",
    "If Alan Wake were an earthquake, he'd be Alan Shake.",
    "If Alan Wake had clinical back pain, he'd be Alan Ache.",
    "If alan was a car part, he'd be Alan Brake.",
    "If Alan was careless, he'd be Alan Break.",
    "If Alan was a reptile, he'd be Alan Snake.",
    "If Alan was a food, he'd be Alan Steak.",
    "If Alan was a body of water, he'd be Alan Lake.",
    "If Alan had insomnia, he'd be Alan Wake.",
    "If Alan was a pastry, he'd be Alan Cake.",
    "If Alan was a virus, he'd be Alan Outbreak.",
    "If Alan was special, he'd be Alan Snowflake.",
    "If alan was good with syrup, he'd be Alan Pancake.",
    "If Alan was Ctrl + Z, he'd be Alan Unmake.",
    "If Alan got dumped, he'd be Alan Heartbreak.",
    "If Alan was an impostor, he'd be Alan Fake.",
    "If Alan channeled air to an engine, he'd be Alan Intake.",
    "If Alan was a craftsman, he'd be Alan Make.",
    "If Alan was a northern African garment, he'd be Alan Haick.",
    "If Alan was not clear, he'd be Alan Opaque.",
    "If Alan was used to Tokyo drift, he’d be Alan Handbrake.",
    "If Alan was cared about, he’d be Alan Keepsake.",
    "If Alan was named Elly, he’d be ip_gaming1's Alan Namesake.",
    "If I told Alan to come eat, he would be Alan Partake.",
    "If Alan worked at Statefarm, he would be Alan Jake.",
    "If Alan was me at 2 AM, he’d be Alan Wide-awake.",
    "If Alan was a rapper, he’d be Alan Drake.",
    "If Alan was dandruff, he’d be Alan Flake.",
    "If Alan was a fish, he’d be Alan Hake.",
    "If Alan was a piece of a boat, he’s be Alan Strake.",
    "If Alan was a muscle pain, he’d be Alan Backache.",
    "If Alan was a nerve pain, he’d be Alan Headache.",
    "If Alan was similar to a muffin, he’d be Alan Cupcake.",
    "If Alan was a hydraulic, he’d be Alan Disc-brake.",
    "If Alan brought all the boys to the yard, he’d be Alan Milkshake.",
    "If Alan was a wasted scene, he’d be Alan Outtake.",
    "If Alan was a plant, he’d be Alan Mandrake.",
    "If Alan joined a club, he’d be Alan Partake.",
    "If Alan was created again, he’d be Alan Remake.",
    "If Alan was a professional racer, he’d be Alan Overtake.",
    "If Alan was easy, he’d be Alan Piece of cake.",
    "If Alan was inaccurate, he’d be Alan Give-or-take .",
    "If Alan accepted a challenge, he’d be Alan Undertake.",
    "If Alan was ridiculously expensive, he’d be Alan Wedding-cake.",
    "If Alan was a sign of agreement, he’d be Alan Handshake.",
    "If Alan was a video game, he’d be Alan Quake.",
    "If Alan was a giveaway, he’d be Alan Sweepstakes.",
    "If Alan was a cereal he’d be Alan cornflakes.",
    "If Alan Wake were a dessert, he’d be Alan Shortcake.",
    "If Alan Wake were a funeral director, he’d be Alan Undertake.",
    "If Alan wake was a funeral, he'd be alan Wake.",
    "If Alan Wake were a bad boy, he’d be Alan Heartbreak.",
    "If Alan Wake were a sad boy, he’d be Alan Heartache.",
    "If Alan Wake were in a roller derby, he’d be Alan Rollerskate.",
    "If Alan Wake were a disgusting Christmas pie, he’d be Alan Fruitcake.",
    "If Alan saw something unbelievable, he'd be Alan Doubletake.",
    "If Alan Wake were a daredevil, he’d be Alan Risk-take.",
    "If Alan Wake were an actor, he’d be Alan Outtake.",
    "If Alan impersonated somebody using CGI, he'd be Alan Deepfake.",
    "If Alan Wake were a hospital receptionist, he'd be Alan Intake.",
    "If Alan Wake was an accident, he'd be Alan Mistake.",
    "If Alan could bring all the boys to the yard, he would be Alan Milkshake.",
    "If Alan was a romantic busybody, he'd be Alan Matchmake.",
    "If Alan slandered you in a news piece, he'd be Alan Muckrake.",
    "If Alan wasn't an artist, he'd be Alan Beefcake.",
    "If Alan Wake had plastic surgery , he'd be Alan Fake.",
    "If Alan Wake was not trustworthy, he'd be Alan Snake.",
    "If Alan Wake ran Potions class, he'd be Alan Snape.",
    "If Alan Wake hit snooze, he'd be Alan Late.",
    "If Alan Wake couldn't pronounce Japanese Rice Wine he'd be Alan Sake.",
    "If Alan Wake was in prison for life but got out, he'd be Alan Jailbreak..",
    "If Alan Wake made the sun rise, he'd be Alan Daybreak.",
    "If Alan Wake were an asshole, he’d be Alan Shit-take.",
    "If Alan wake satisfied, he'd be alan Slake.",
    "If Alan Wake were fancy, he’d be Alan Cheesecake.",
    "If Alan was popular, he'd be Alan Hotcake.",
    "If Alan was a mushroom, he'd be Alan Shiitake.",
    "If Katy Perry made a song about Alan Wake, he'd be Alan Wideawake.",
    "If Alan was pissed, he'd be Alan FOR FUCKS SAKE."
];